name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Lint src
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: './src'
          extensions: 'h,c'
          clangFormatVersion: 12.0.0

      - name: Lint libsol
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: './libsol'
          extensions: 'h,c'
          clangFormatVersion: 12.0.0

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Check misspellings
        uses: codespell-project/actions-codespell@v1
        with:
          builtin: clear,rare
          check_filenames: true
          path: src/,libsol/,Makefile,README.md,doc/
          skip: ./libsol/printer_test.c
